project:
  type: website
  output-dir: "docs"
lang: fr
website:
  title: "MedGachis"
  search:
    location: sidebar
    type: textbox
  page-footer:
    left: "Copyright 2025, philippe MICHEL"
    right:
      - icon: github
        href: https://github.com/philippemichel
      - icon: twitter
        href: https://twitter.com/PhiippeMICHEL
      - icon: mailbox
        text: mail
        href: mailto:docphilmstat@gmail.com
  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents:
      - section: "MedGachis"
        contents:
          - index.qmd
          - patients.qmd
          - bloc.qmd
          - traitement.qmd
  open-graph:
    locale: fr_FR
    site-name: MedGachis
format:
  html:
    page-layout: full
    highlight-style: ayu
    code-fold: true
    theme:
      light:
        - sandstone
      dark: cyborg
    fontsize: 1.2em
    toc: true
    warning: false
    message: false
    eval: true
